### ISSUE TITLE
Could you please add ue5 support

### ISSUE THREAD

**Issue by ameaninglessname** [fpwong/AutoSizeComments#10]
Such as add a ue5-main branch

**Comment by ameaninglessname** [comment]
https://github.com/fpwong/AutoSizeComments/blob/966615dfeb3a2baa4de237b05e111c1f5f2bd07f/Source/AutoSizeComments/Public/AutoSizeCommentsGraphNode.h#L50

I was changing this line to 
`#if ENGINE_MAJOR_VERSION == 4 && ENGINE_MINOR_VERSION >= 27 || ENGINE_MAJOR_VERSION == 5`
to successfully compiled in ue5

and 
I "#define"d that line to reuse elsewhere.

**Comment by fpwong** [comment]
Here you go, I don't have the main branch right now so I'm not sure if it builds correctly. Feel free to add any pull requests if stuff breaks in the future.

https://github.com/fpwong/AutoSizeComments/tree/ue5-main
