### ISSUE TITLE
Comments not showing bubbles and setting checked all the time

### ISSUE THREAD

**Issue by Dvoya** [fpwong/AutoSizeComments#11]
![image](https://user-images.githubusercontent.com/60451976/142251750-c35932f6-56b8-4326-bef0-039c64ee58d0.png)
The text in the comment should be appearing as a bubble when zoomed out, but it doesn't, and I can't seem to uncheck the option for bubble appearing. I'm on 4.27.1 with the latest version of autosizecomments.

**Comment by fpwong** [comment]
Oh another user recently reported this as well. I actually pushed a commit to fix this recently but forgot to push the update to the marketplace 😦

Will ping you again when the update is live or you can build it from github if you'd like

**Comment by fpwong** [comment]
Should be fixed in 3.0.2
