### ISSUE TITLE
Comments get deleted in Niagara

### ISSUE THREAD

**Issue by tigerija** [fpwong/AutoSizeComments#12]
Happens in UE4.27 and UE5 as well.
Open Niagara, add comment, close, reopen, comment wont be there anymore. :(

**Comment by fpwong** [comment]
Hi tigerija, sorry I was not able to replicate this issue on 4.27. A few questions:

* By close / reopen, is this "close the file and reopen" or "close the project and reopen"?
* What version of the plugin are you on?
* Which niagara graph type does this happen on?

**Comment by tigerija** [comment]
Update: I think this might be an Unreal bug. And not your addon. I apologize in that case - because I only noticed that once using your great addon. But after some testing it seems like its bug with Unreal, and so far only with Niagara Emitters.
I tested on both UE 4 and 5, with and without your plugin. Same thing happens.

- By close / reopen, is this "close the file and reopen" or "close the project and reopen"?
- - Create new Niagara Emitter
- - Add comment. Save.
- - Close Niagara Emitter.
- - Open Niagara Emitter.
- - Comments should not be there anymore.

- What version of the plugin are you on?
- - Latest from Marketplace. 	"VersionName": "3.0.2",


- Which niagara graph type does this happen on?
- - Emitter.

**Comment by fpwong** [comment]
Thanks for the testing this indepth, I am able to replicate this bug now. I'm pretty sure I tested all the other niagara types except Emitter haha, they don't seem to have the same issue.

Suggest you submit a bug report to Unreal if you haven't already 😃
