### ISSUE TITLE
Cannot drag off pins in an animation blueprint since the last update.

### ISSUE THREAD

**Issue by tmdtyran** [fpwong/AutoSizeComments#14]
Since the last update it is impossible to drag off pins e.g. from an animation state machine. The bug only happens in the Animation Graph and not in the event graph of the Animation Blueprint.

**Comment by fpwong** [comment]
Hi tmdtyran, I have pushed the fix, it should be out tomorrow. 

If you'd like to fix it temporarily you can disable the setting `Select Node when Clicking on Pin`. However disabling this will make the auto insert comment behaviour not work correctly.

**Comment by fpwong** [comment]
This should be fixed in 3.0.5

**Comment by tmdtyran** [comment]
Thank you for the hard work

**Comment by fpwong** [comment]
It appears the update did not go through on the marketplace even though I recieved a confirmation email from them. I will have to contact them to see what has happened. Reopening this issue for now.

You can download the packaged version of 3.0.5 here: https://drive.google.com/drive/folders/1vjfl4bUBoykyii4FdYVGYckFTJtJ4r4z?usp=sharing

**Comment by fpwong** [comment]
The hotfix is now on the marketplace, please update the plugin again.

**Comment by tmdtyran** [comment]
Hello fpwong,

I downloaded it.
Thank you for the fast fix

Cheers
