### ISSUE TITLE
Cannot drag off nodes in behavior trees

### ISSUE THREAD

**Issue by unrealengine4u** [fpwong/AutoSizeComments#15]
When plugin enabled I cannot drag off / connect anything in a behavior tree.
here is a clip to show: [https://i.gyazo.com/0f3da4a87d516a5c6a8ce0df58fe4dfd.mp4](url)

I can confirm however that the same temporary fix for Issue #14 does work also for this issue (i assume they are related issues at core :) )

**Comment by fpwong** [comment]
Hi, yes this is the same issue as #14. This should be fixed now in 3.0.5.
