### ISSUE TITLE
UE 5.0.3 Missing Header Files

### ISSUE THREAD

**Issue by etoven** [fpwong/AutoSizeComments#20]
Build tool won't run
Appears to be missing header files

![image](https://user-images.githubusercontent.com/8019624/181870720-4e6c595b-4110-4fc6-b636-1d4cda3a2ccc.png)

**Comment by etoven** [comment]
I just noticed the file is in the directory. Maybe not included in the project?
Not sure what's going on.

**Comment by fpwong** [comment]
Hmm I'm not really sure whats going on here either. Did this work fine on the older plugin version / UE version?

Since this is the only error, I'd guess it might be because there is no `AutoSIzeCommentsMacros.cpp` file? Could you try creating this file in the Private folder with just the line `#include "AutoSIzeCommentsMacros.h"` and then rebuilding. Let me know if that fixes it.

**Comment by etoven** [comment]
In 5.0.0 building worked for prior version. Will try as you suggested and let you know for this one on 5.0.3.

**Comment by etoven** [comment]
I just noticed something. The header is referencing a file with a lowercase I AutoSizeCommentsMacros while the actual .h and cpp are names AutoSIzedCommentsMacros.h with Uppercase I

**Comment by etoven** [comment]
Updating the header in AutoSIzedCommentsGraphNode.cpp got me further. 
```
#pragma once

#include "CoreMinimal.h"
-#include "AutoSizeCommentsMacros.h"
+#include "AutoSIzeCommentsMacros.h"
#include "SGraphNode.h"

enum class ECommentCollisionMethod : uint8;
class SCommentBubble;
class UAutoSizeCommentsSettings;
struct FASCCommentData;
struct FPresetCommentStyle;
class UEdGraphNode_Comment;

DECLARE_STATS_GROUP(TEXT("AutoSizeComments"), STATGROUP_AutoSizeComments, STATCAT_Advanced);
```
But now failing on AutoSizeCommentsCacheFile.cpp because /Core/Public/HAL/PlatformFileManager.h not found. 

![image](https://user-images.githubusercontent.com/8019624/181920853-7a8186f8-8c7b-4453-b22f-2d5801b417f9.png)

**Comment by etoven** [comment]
Looks like that should be `PlatformFileManager.h`.. ha hundi engine had that same bug on that one. Manager with capital M Trying another build

**Comment by etoven** [comment]
LOL the camelcase saga continues.
Got further still. Fixing this one as well.
I'll put all this in a pull request for you BTW.

![image](https://user-images.githubusercontent.com/8019624/181922156-1d51c8b7-f952-440d-97f0-ca3f58a41957.png)

**Comment by etoven** [comment]
Mission Success! +50xp
![image](https://user-images.githubusercontent.com/8019624/181923506-9a5bf1c9-eb1c-4eda-8322-0087c76cd281.png)

**Comment by etoven** [comment]
Pull request is in.

**Comment by fpwong** [comment]
Thanks etoven, really would have never figured these out. I'm going to rename the `AutoSizeCommentsMacros.h` file itself instead of fixing up the headers. I think the `PlatformFileManager.h` was renamed with a capital `M` in UE5, so I trust you're going to have to fix up all the plugins which use this haha.

[+ 100 xp]

**Comment by etoven** [comment]
> Thanks etoven, really would have never figured these out. I'm going to rename the `AutoSizeCommentsMacros.h` file itself instead of fixing up the headers. I think the `PlatformFileManager.h` was renamed with a capital `M` in UE5, so I trust you're going to have to fix up all the plugins which use this haha.
> 
> [+ 100 xp]
> 
> Edit: Would love to show some sort of error for case sensitive headers when you compile on windows. Some googling didn't find any answers though. Let me know if anyone has a way of enabling this.

I'm mainly glad my comments are tidy. Serenity again. :)
I'm not sure. I mainly develop on linux. 

Maybe try unreal's script instead of visual studio if that's what your using currently. 
I suspect it's a quirk of the toolchain being used.

I made a sh I use that wraps to the unreal native toolchain
`'<Engine Install>/Engine/Build/BatchFiles/RunUAT.sh' BuildPlugin -plugin="${1}" -Package="${2}"`

There is a batch file also that gets installed however in the same directory you could use:
`'<Engine Install>/Engine/Build/BatchFiles/RunUAT.bat' BuildPlugin -plugin="${1}" -Package="${2}"

Where ${1} is the .uplugin file and ${2} is the build location

**Comment by etoven** [comment]
BTW:
If you want to reopen the bug. I can update this PR for you.

**Comment by fpwong** [comment]
It appears to be due to Windows vs Linux. This is someone's reply from a old forum post about the same issue:

> But it is not problem of
> compiler, it is problem of filesystem, because on FAT or NTFS are
> always files, which differ only in upper/lower case letters, treated as
> same files. You can try it with gcc on Windows, there is the same problem.

Seems to be quite an annoying issue, I think I'd need to use an external tool to check for this problem

> If you want to reopen the bug. I can update this PR for you.

Thanks but I have already just pushed the fix for this here: https://github.com/fpwong/AutoSizeComments/commit/e87d712b2ae0408c49fc3f7bfa9ea6bb7960d7da

**Comment by etoven** [comment]
> It appears to be due to Windows vs Linux. This is someone's reply from a old forum post about the same issue:
> 
> > But it is not problem of
> > compiler, it is problem of filesystem, because on FAT or NTFS are
> > always files, which differ only in upper/lower case letters, treated as
> > same files. You can try it with gcc on Windows, there is the same problem.
> 
> Seems to be quite an annoying issue, I think I'd need to use an external tool to check for this problem
> 
> > If you want to reopen the bug. I can update this PR for you.
> 
> Thanks but I have already just pushed the fix for this here: [e87d712](https://github.com/fpwong/AutoSizeComments/commit/e87d712b2ae0408c49fc3f7bfa9ea6bb7960d7da)

I just noticed. I can check your commit if you would like.

**Comment by fpwong** [comment]
> I just noticed. I can check your commit if you would like.

Yes, that would be great 👍

**Comment by etoven** [comment]
Trying a fresh pull now. I'm also compiling over 3,552 shaders so it could be a minute. LOL

**Comment by etoven** [comment]
Looks like one was missed in AutoSizeCommentsGraphHandler.h
`fatal error: 'AutoSIzeCommentsMacros.h' file not found
`

**Comment by etoven** [comment]
I'm checking the rest now

**Comment by etoven** [comment]
I rebased to [e87d712](https://github.com/fpwong/AutoSizeComments/commit/e87d712b2ae0408c49fc3f7bfa9ea6bb7960d7da) I will submit a new PR.
