### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by fpwong** [fpwong/AutoSizeComments#26]
@fpwong is this supposed to be working now? I'm on 3.1.4 but I'm seeing this:
![image](https://user-images.githubusercontent.com/40641737/207722137-14770a89-3a19-4d59-814a-e18e1284eb2d.png)

Same issue for AutoSizeComments and BlueprintAssist on custom UE5 engine; idk if that's our problem or plugin's.

---
[Update]Huh, when trying to reference and build from source, nothing is really being generated. Idk if this is my fault or what, the same setup worked for UE4 anyway. 

I noticed this [plugin author](https://gamedev.stackexchange.com/questions/200626/porting-plugins-from-ue5-0-to-ue5-1-source-build-causes-dll-registration-errors) was trying to port their plugin to UE5 source compiled and ran into the same issue, so it leads me to believe it's a plugin configuration issue or something for custom UE5 built engines.

_Originally posted by @leetNightshade in https://github.com/fpwong/AutoSizeComments/issues/25#issuecomment-1352252502_

**Comment by fpwong** [comment]
I would say most likely an issue on your side. I have tested the plugin on source built UE5 by placing the plugin the project folder and building from there.

Did you put the plugin in your `Engine/Plugin` folder or your `Project/Plugin` folder?

Also do you have any other code plugins installed and do they have this issue?

**Comment by leetNightshade** [comment]
I put them in my project's `Engine/Plugin/Marketplace`, but maybe I shouldn't put them there. We have a lot of other plugins, nothing else has this problem, but most of those are in `Game/Plugins`. Heh, I'll just try putting them there, I only put them in Engine because that's where the Program Files one was placed when I downloaded it. Sounds stupid doesn't it. 😅

**Comment by leetNightshade** [comment]
Sorry that was it. It compiled fine for me in UE4's `Engine/Plugin/Marketplace`, but not in UE5's.
