### ISSUE TITLE
Reroute nodes aren't added to the comment boxes when they are refreshed

### ISSUE THREAD

**Issue by realityrig** [fpwong/AutoSizeComments#4]
It looks like reroute nodes are ignored when nodes are being added to comment boxes in the "RefreshNodesInsideComment" function.

So, if you select a group of nodes that includes reroute nodes and then add them manually to a comment, and then move the comment box around, then it seems like it works and the reroute nodes move. But then if you save the BP and load it later, and try to move that same comment box... then it seems like the reroute nodes don't move with the comment box.

Line 533-534 of AutoSizeCommentNode.cpp say:
`// skip knot nodes`
`if (Cast<UK2Node_Knot>(GraphObject)) continue; `

I tested taking those lines out, and didn't notice any negative side effects. Any issues that you can think of that might crop up if those lines are removed?

**Comment by fpwong** [comment]
Ah I believe this was related to an interaction with the blueprint assist plugin where I was recreating the knot nodes. Removing these lines should not be a problem now. https://github.com/fpwong/AutoSizeComments/commit/98a40fab9903b27597dfff64451f76edaa863b9d
