### ISSUE TITLE
Crash when editor startup (3.0.0)

### ISSUE THREAD

**Issue by yuanb36** [fpwong/AutoSizeComments#9]
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000001d00000011

UE4Editor_Engine!UEdGraphNode::GetGraph() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\EdGraph\EdGraphNode.cpp:452]
UE4Editor_AutoSizeComments!FAutoSizeCommentGraphHandler::UpdateContainingComments() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\AutoSizeComments\Source\AutoSizeComments\Private\AutoSizeCommentsGraphHandler.cpp:205]
UE4Editor_Engine!FTimerUnifiedDelegate::Execute() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Public\TimerManager.h:51]
UE4Editor_Engine!FTimerManager::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\TimerManager.cpp:881]
UE4Editor_UnrealEd!UEditorEngine::Tick() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1367]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:426]
UE4Editor!FEngineLoop::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4836]
UE4Editor!GuardedMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
UE4Editor!GuardedMainWrapper() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
UE4Editor!WinMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by fpwong** [comment]
Hi yuanb36. I am not sure why this is happening, especially on editor startup. Is there any chance you have some sort of graph opened when you startup the editor?

I have tested the setting `Restore Open Asset Tabs on Restart` but that did not cause a crash.

**Comment by yuanb36** [comment]
Assets won't be opened until you click the "Restore" button on the bottom right notification bar. So I think it's not due to opening an asset. Some background process caused the crash.
And I tried to disable the plugin in the .uproject file and start the editor and closed all assets window, enabled the plugin and started the editor again, it also crashes.
If I rollback it to 2.4.0, it won't crash.

The only graph I can think of is the Logic Driver Pro plugin I am using, it utilizes some new blueprint graph. But it's OK when in 2.4.0. And I can not reproduce the same crash on a new project. If you are interested you can try its free version on the marketplace. I have thought of deleting all the comments in those graphs, but it is just too much work.

**Comment by yuanb36** [comment]
Another log, sometimes it is like this, I think it is the same issue.


Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000008

UE4Editor_AutoSizeComments!FAutoSizeCommentGraphHandler::UpdateContainingComments() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\AutoSizeComments\Source\AutoSizeComments\Private\AutoSizeCommentsGraphHandler.cpp:200]
UE4Editor_Engine!FTimerUnifiedDelegate::Execute() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Public\TimerManager.h:51]
UE4Editor_Engine!FTimerManager::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\TimerManager.cpp:881]
UE4Editor_UnrealEd!UEditorEngine::Tick() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1367]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:426]
UE4Editor!FEngineLoop::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4836]
UE4Editor!GuardedMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
UE4Editor!GuardedMainWrapper() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
UE4Editor!WinMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by fpwong** [comment]
Thanks for the info. I just pushed an update to github now, which might have fixed the issue. I'll test out the Logic Driver plugin in a second too.

Let me know what version of UE you are running and I'll send you a built version of the plugin.

**Comment by yuanb36** [comment]
Hello, I just noticed you updated to 3.0.1, and I am compiling myself. I will give it a try in a moment. I'm using official 4.26.2 version.

**Comment by yuanb36** [comment]
I have just done a quick test, no crashes happen, it may be fixed. Thank you.

**Comment by fpwong** [comment]
That's great! Honestly I did not think this change would fix it but thankfully it seems to have worked 😄
